apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    service: agent
  name: agent
  namespace: gleam
spec:
  replicas: 3
  selector:
    matchLabels:
      service: agent
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        service: agent
    spec:
      containers:
      - name: agent
        image: eisokant/gleam
        volumeMounts:
          - name: gleam-disk
            mountPath: /data
        resources:
          limits:
            memory: "2Gi"
            cpu: "0.3"
        args:
          - "agent"
          - "--memory=2048 --master=master:45326"
      volumes:
        - name: gleam-disk
          gcePersistentDisk:
            pdName: gleam-disk
            fsType: ext4

