apiVersion: v1
kind: PersistentVolume
metadata:
  name: gleam-disk-volume
spec:
  capacity:
    storage: 3000Gi
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: gleam-disk
    fsType: ext4