apiVersion: v1
kind: Pod 
metadata:
  name: temp
  namespace: gleam
spec:
    volumes:
    - name: gleam-data
      persistentVolumeClaim:
        claimName: gleam-pvc
        readOnly: true
    containers:
    - name: temp
      image: alpine
      command: ["tail"]
      args: ["-f", "/dev/null"]
      volumeMounts:
      - name: gleam-data
        mountPath: /data
        
    restartPolicy: Never