apiVersion: v1
kind: Service
metadata:
  labels:
    service: pprof
  name: agent
  namespace: gleam
spec:
  ports:
  - name: pprof
    port: 8080
    protocol: TCP
  clusterIP: None
  selector:
    service: agent