apiVersion: batch/v1
kind: Job 
metadata:
  name: multitool
spec:
  template:
    spec:
      containers:
      - name: multitool-container
        image: eisokant/multitool
        args: ["download-dataset"]
      restartPolicy: Never