FROM alpine:latest
MAINTAINER Eiso Kant <eiso@sourced.tech>

RUN mkdir /lib64 && ln -s /lib/libc.musl-x86_64.so.1 /lib64/ld-linux-x86-64.so.2
RUN apk --update add git openssh curl htop

VOLUME /data

WORKDIR /

COPY driver /driver
RUN chmod +x /driver

COPY docker/entrypoint_driver.sh /entrypoint_driver.sh
RUN chmod +x /entrypoint_driver.sh

ENTRYPOINT ["/entrypoint_driver.sh"]