FROM alpine:latest
MAINTAINER Eiso Kant <eiso@sourced.tech>

RUN mkdir /lib64 && ln -s /lib/libc.musl-x86_64.so.1 /lib64/ld-linux-x86-64.so.2
RUN apk --update add git openssh curl jq

WORKDIR /tmp

COPY pga /usr/bin/
COPY docker/entrypoint_pga.sh /entrypoint_pga.sh

RUN chmod +x /entrypoint_pga.sh

ENTRYPOINT ["/entrypoint_pga.sh"]