FROM debian:jessie-slim
MAINTAINER Eiso Kant <eiso@sourced.tech>

VOLUME /data

WORKDIR /

COPY driver /driver
RUN chmod +x /driver

COPY docker/entrypoint_driver.sh /entrypoint_driver.sh
RUN chmod +x /entrypoint_driver.sh

ENTRYPOINT ["/entrypoint_driver.sh"]